#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, CLEAR, MOUSE, PLUS, MINUS, FRONT, BACK};
enum COLOR {RED, ORANGE, YEllOW, BLUE, INDIGO, VIOLET};

#endif